# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: debian:10-slim
 
cache:
  paths:
    - node_modules/

test_vue:
  before_script:
  - npm install json-server
  - json-server -w db.json -r routes.json -m middleware.js >/dev/null &

  script:
    - npm install
    - npm test
    - killall json-server >/dev/null

  after_script:
    - /bin/bash -c '/usr/bin/killall -q json-server; exit 0'
