image: docker:latest

stages:
  - build_image
  - test
  - deploy_image

variables:
  PROGRESSION_DIR: $CI_PROJECT_DIR
  DOCKER_HOST: "tcp://dind:2375"

# Stage test

# Tests unitaires
test_unitaires:
  stage: test
  services:
  - name: git.dti.crosemont.quebec:5050/progression/dind_workaround:latest
    command: ["--tls=false"]
    alias: dind
  script:
    - true

# Stage build_image

# Construction de l'image
const_image:
  stage: build_image
  services:
  - name: git.dti.crosemont.quebec:5050/progression/dind_workaround:latest
    command: ["--tls=false"]
    alias: dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY/progression/progression_frontend:test .
    - docker push $CI_REGISTRY/progression/progression_frontend:test
  only:
    - dev
    - master


# Stage deploy_image

# Déploiement sur /staging
deploy:
  stage: deploy_image
  needs: [const_image]
  services:
  - name: git.dti.crosemont.quebec:5050/progression/dind_workaround:latest
    command: ["--tls=false"]
    alias: dind
  script:
    - chmod 400 /builds/progression/progression_frontend.tmp/ID_RSA
    - ssh -i $ID_RSA -o StrictHostKeyChecking=no $CD_USER@$CD_HOST -p $CD_PORT $CD_COMMAND test $CI_COMMIT_REF
  only:
    - master
    - dev
