# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: 
  - debian:10-slim
 
cache:
  paths:
    - node_modules/
 
before_script:
  - docker info
 
test_vue:
  script:
    - npm install
    - docker build -t jsonserver .
    - docker run --rm -it --name jsonserver-container -p 3000:3000 jsonserver
    - npm test
