version: '3.5'

services: 
  app:
    image: $CI_REGISTRY/$CI_PROJECT_PATH:$TAG_DEPLOY
    container_name: progression_app_$CI_ENVIRONMENT_SLUG
    ports:
      - 127.0.0.1:$INSTANCE_PORT:8080
    env_file:
      - "$ENV_FILE"
      - VERSION

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
      ME_CONFIG_SITE_BASEURL: /mongo/
    ports:
      - 8081:8081    

  ltijs:
    build: ltijs/
    restart: always
    ports:
      - 3000:3000
    environment:
      DB_HOST: 172.20.0.4
      DB_NAME: ltijs
      DB_USER: root
      DB_PASS: example
      LTI_KEY: w#np)xp!BE!2hLsbk}pR
      DEBUG: provider:*
    depends_on:
      - mongo
        
  tests_app: 
    image: $CI_REGISTRY/$CI_PROJECT_PATH:$TAG_DEPLOY
    command: npm run test:run

  linter:
    image: $CI_REGISTRY/$CI_PROJECT_PATH:$TAG_DEPLOY
    command: npx eslint -c eslintrc.js src/**/*.{js,vue}        
