version: '3.5'

services: 
  mock:
    build: ./mock/
    ports:
      - 3000:3000
  app:
    build: ./
    ports:
      - 8080:8080
    #Pour le développement  
    volumes:
      - "./app/src:/app/src"
      - "./app/public:/app/public"
    networks:
      default:
        ipv4_address: 172.20.0.6

networks:
  default:
    external:
      name: progression_backend_master_progressionnet

# command to build
#   docker-compose build

# command to run
#   docker-compose up

# command to stop
#   docker-compose stop
# command to stop and remove container image
#   docker-compose rm -f -s

# Ajouter sudo devant chaque commande si nécessaire

# url front-end => http://localhost:8080
# url mock => http://localhost:3000

